### ISSUE TITLE
Initial App State with routes populated isn't rendered correctly

### ISSUE THREAD

**Issue by wtsnz** [darrarski/swift-composable-presentation#20] opened 2021-11-24 19:43 UTC
## Summary

I've experienced an issue where it seems that "deep linking" more than 1 screen (via NavigationLink) "down" doesn't work as expected.

## Steps to reproduce

1. Replace the body function in the `PopToRootExample.swift` with the following:

```swift
  var body: some View {
    NavigationView {
      RootView(store: Store(
        initialState: RootState(
            timer: .init(),
            first: .init(
                timer: .init(),
                second: .init(timer: .init())
            )
        ),
        reducer: Self.rootReducer.debug(),
        environment: ()
      ))
    }
    .navigationViewStyle(StackNavigationViewStyle())
  }
```

2. Run the app
3. Tap the "Pop To Root Example"

## Expected behavior

I'd expect the app to display the Second Screen in the PopToRoot Example.

## Actual behavior

The app opens up displaying the First Screen, and tapping the "Present Second" button doesn't do anything.

**Comment by darrarski** [comment] 2021-11-24 20:14
Thanks for reporting the issue. I’ll let you know once I investigate the problem.

**Comment by darrarski** [comment] 2021-11-24 20:22
@wtsnz could you create a PR with the changes you made to the example app? There is no `DemoApp.swift` file In the project, nor the `DemoAppState` struct you mentioned, so I am a bit confused.

**Comment by wtsnz** [comment] 2021-11-24 20:55
@darrarski I'm so sorry about that, I must have been confused and have been looking at another TCA Navigation example 🙈 

The issue I'm facing also happens with this repo - and I've updated my initial issue with the relevant details with this example project.

**Comment by darrarski** [comment] 2021-11-25 14:36
@wtsnz I've investigated the problem. It's 100% reproducible on the iOS 15.0 Simulator (Xcode 13.1). 

The navigation link on `FirstView` that presents `SeondView` is active, but the view does not represent this state (the `SecondView` is not presented). I don't think we can do anything about it. I assume it's a "SwiftUI on iOS simulator" kind of bug. 

The good news is that it only occurs when running in the simulator. I tried on a physical device (iPhone Xs, iOS 15.1) and was not able to reproduce it. I think I heard about `SwiftUI.NavigationLink` being broken on the simulator a couple of times in the past, so this could be it.

I am closing the issue, feel free to comment if you have any questions.

**Closed by darrarski** 2021-11-25 14:36 UTC
Labels: bug

**Comment by wtsnz** [comment] 2021-11-25 17:14
@darrarski you're amazing. Thanks for looking into the issue! 

I hadn't thought that it could be a device/simulator issue because I can reproduce the issue on my device running iOS 14.5.1 - Xcode 13.1. I guess it's time to update and drop support for iOS14.

Sounds like this issue is due to SwiftUI 🤷😞
